{% set name = "scine-molassembler" %}
{% set version = "3.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

# Note: Python bindings can't be built separately from library, due to symbol visibility.
#       Some symbols are only visible in an intermediary static library which is used
#       to link the Python bindings, but not installed.
#       See https://github.com/qcscine/molassembler/issues/8

source:
  - url: https://github.com/qcscine/molassembler/archive/refs/tags/{{ version }}.tar.gz
    sha256: 78e00e141dd3da74f9cac6b8ce58e3980153526daf25cebd3d435e757387e408
    patches:
      # See https://github.com/qcscine/molassembler/issues/4
      - patches/nlohmann_json.patch
      # See https://github.com/qcscine/molassembler/issues/3
      - patches/nauty_thread_local.patch
      # See https://github.com/qcscine/molassembler/issues/7
      - patches/no_duplicate.patch
      # https://github.com/qcscine/molassembler/issues/5
      - patches/no_cfenv.patch
  - url: https://github.com/qcscine/development-utils/archive/refs/tags/5.0.1.tar.gz
    sha256: 089ca500fc191e04a968ea166d2fe80178b227bc2e6d3926523fa2eee5f6492d
    folder: dev
    patches:
      # See https://github.com/qcscine/development-utils/issues/2
      - patches/pybind11_pin.patch

build:
  number: 0
  skip: true  # [win]

  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - pybind11                            # [build_platform != target_platform]
  host:
    - boost-cpp
    - eigen
    - gtest
    - gmock
    - nauty
    - libblas  # [linux]
    - pip
    - python
    - pybind11
    - pybind11-abi
    - nlohmann_json
    - ringdecomposerlib
    - scine-utilsos
  run:
    - boost-cpp
    - nauty
    - python
    - scine-utilities-python

test:
  imports:
    - scine_molassembler
  requires:
    - pip
  commands:
    - test -f $PREFIX/lib/libmolassembler${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libmolassembler.a
    - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    Chemoinformatics toolkit with support for inorganic molecules
  description: |
    Molassembler is a C++ library that aims to facilitate conversions between
    Cartesian and graph representations of molecules. It provides the necessary
    functionality to represent a molecule as a graph, modify it in graph space,
    and generate new coordinates from graphs. It can capture the absolute configuration
    of inorganic molecules with multidentate and haptic ligands from Cartesian
    coordinates and enumerate non-superposable stereopermutations at non-terminal
    atoms and non-isotropic bonds at arbitrary local shapes ranging up to the
    icosahedron and cuboctahedron.
  home: https://scine.ethz.ch/download/molassembler
  dev_url: https://github.com/qcscine/molassembler
  doc_url: https://scine.ethz.ch/static/download/documentation/molassembler/v{{ version }}/cpp/

extra:
  recipe-maintainers:
    - awvwgk
